services:
  - type: web
    name: comite-olimpico-api
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/comiteolimpicoapi-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free